version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  minio:
    image: bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}


  app:
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: ${DB_PORT}
      UPLOAD_FOLDER: ${UPLOAD_FOLDER}
      BOTO_URL: ${BOTO_URL}
      BOTO_DEFAULT_BUCKET: ${BOTO_DEFAULT_BUCKET}
      MODE_STORAGE: ${MODE_STORAGE}
      PROFILE_NAME: ${PROFILE_NAME}
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_LIFETIME: ${ACCESS_LIFETIME}
      REFRESH_LIFETIME: ${REFRESH_LIFETIME}
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./boto/credentials:/root/.aws/credentials
      - ./src:/app/src

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}