version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  minio:
    image: bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minio-root-user
      MINIO_ROOT_PASSWORD: minio-root-password


  app:
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_NAME: filestorage
      DB_USER: root
      DB_PASSWORD: root
      DB_PORT: 5432
      UPLOAD_FOLDER: '/downloads'
      BOTO_URL: 'http://minio:9000'
      BOTO_DEFAULT_BUCKET: default
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./boto/credentials:/root/.aws/credentials
      - ./src:/app/src

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: filestorage
      POSTGRES_USER: root